### ISSUE TITLE
what is linux?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/linux-preparation#13]
Linux® is an open source operating system (OS). An operating system is the software that directly manages a system’s hardware and resources, like CPU, memory, and storage.

**Comment by JQuarticx** [comment]
Explanation

 Its operating system. opensource

Reference

**Comment by armyforce** [comment]
Linux is a free open source operating system
Anyone can read study and use this
linux is a command line interface

**Comment by JQuarticx** [comment]
superb

**Comment by JQuarticx** [comment]
Approved
