### ISSUE TITLE
what the key components available in linux?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/linux-preparation#14]
please explore?

**Comment by armyforce** [comment]
Bootloader. Your computer needs to go through a startup sequence called booting. ...
OS Kernel. ...
Background services. ...
OS Shell. ...
Graphics server. ...
Desktop environment. ...
Applications.

**Comment by armyforce** [comment]
PFA Link

https://www.plesk.com/blog/various/what-is-linux/

**Comment by JQuarticx** [comment]
good
