### ISSUE TITLE
what is service in Linux and what is the purpose of it?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/linux-preparation#18]
daemon:-
A daemon is a background, non-interactive program. It is detached from the keyboard and display of any interactive user. The word daemon for denoting a background program is from the Unix culture; it is not universal.

service:-
A service is a program which responds to requests from other programs over some inter-process communication mechanism (usually over a network). A service is what a server provides. For example, the NFS port mapping service is provided as a separate portmap service, which is implemented as the portmapd daemon.

**Comment by armyforce** [comment]
ntpd – Network Time Protocol Daemon
httpd – Hyper Text Transfer Protocol Daemon
sshd – Secure SHell Daemon
sendmail – Mail Server Daemon
snmpd – Simple Network Management Protocol Daemon
iptables – Network Filtering Protocol Service
nfsd – Network File System Server Daemon
nscd – Name Service Cache Daemon
named – Dynamic Naming Service Server Daemon
smbd –  Simple Message Block Server Daemon

**Comment by armyforce** [comment]
PFA reference link for services


https://unixadminschool.com/blog/2012/05/ten-most-frequently-used-linux-networing-services-in-enterprise-networks/

**Comment by JQuarticx** [comment]
i am asking about service. not a list of service
