### ISSUE TITLE
Ensure the root login is disabled?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/linux-preparation#3]
Ensure the root login aws disabled?

**Comment by FourTimes** [comment]
please provide the clarity?

**Comment by FourTimes** [comment]
each linux os having root user. this root user cannot to allowed to ssh in linux server?

**Comment by dodonotdo** [comment]
ok.

**Comment by dodonotdo** [comment]
error for login user authentication
![image](https://user-images.githubusercontent.com/91359308/140717653-5ff3c5f8-0bf7-49f2-a1e0-4a57651aacd0.png)

**Comment by JQuarticx** [comment]
please update the what is the purpose of -i

**Comment by JQuarticx** [comment]
if you are using the key file. you have to mention -i or else its not required

**Comment by JQuarticx** [comment]
key file => ssh -i keyfilename username@Ipaddress

**Comment by JQuarticx** [comment]
password authentication 

ssh username@Ipaddress

**Comment by fourtimes** [comment]
root login was disable.

output:
![image](https://user-images.githubusercontent.com/91359308/140719349-b247a12b-405a-4f4f-acf0-2fdd8af6a48c.png)

**Comment by JQuarticx** [comment]
its approved
