### ISSUE TITLE
Please change the SSH Port22 to 10000?

### ISSUE THREAD

**Issue by JQuarticx** [FourTimes/linux-preparation#4]
Please change the SSH Port22 to 10000?

The following commands we used:
1. open up the vim file: sudo vim /etc/ssh/sshd_config
2. to change port 10000 : port 10000
3.validate the file : sudo sshd -t
4. restart : sudo systemctl restart ssh
output:
![image](https://user-images.githubusercontent.com/91359308/140727671-97827481-d139-4b9f-8a71-612fc99d53e4.png)

**Comment by fourtimes** [comment]
validation: error

![image](https://user-images.githubusercontent.com/91359308/140720077-62e33a63-79f2-4cf3-a541-833ea673fa8f.png)

**Comment by JQuarticx** [comment]
use sudo

**Comment by JQuarticx** [comment]
please ensure this scenario

**Comment by JQuarticx** [comment]
screenshot also required?

**Comment by dodonotdo** [comment]
output:
![image](https://user-images.githubusercontent.com/91359308/140726174-31f4b04e-b52a-4d32-9070-20734cebeb17.png)

**Comment by JQuarticx** [comment]
use this command sudo netstat -tulpn | grep 10000

**Comment by JQuarticx** [comment]
it should return the value.

**Comment by JQuarticx** [comment]
good
